CREATE TABLE dbo.CompanyRecords (
	Id BIGINT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Exchange NVARCHAR(100) NOT NULL,
	StockTicker NVARCHAR(20) NOT NULL,
	ISIN NVARCHAR(12) UNIQUE NOT NULL,
	Website NVARCHAR(255) NULL
);